CREATE TABLE tt_content (
        subheader TEXT,
        image_2 INT(11) UNSIGNED DEFAULT '0' NOT NULL,
        image_3 INT(11) UNSIGNED DEFAULT '0' NOT NULL,
        image_4 INT(11) UNSIGNED DEFAULT '0' NOT NULL,
        background_image INT(11) UNSIGNED DEFAULT '0' NOT NULL,
        quote_text TEXT,
        quote_number VARCHAR(50) DEFAULT '' NOT NULL,

        about_title TEXT,
        about_heading TEXT,
        about_image INT(11) UNSIGNED DEFAULT '0' NOT NULL,
        customer_percentage INT(11) DEFAULT '0' NOT NULL,
        mission_title TEXT,
        mission_text TEXT,
        vision_title TEXT,
        vision_text TEXT,
        read_more_link TEXT,
        facility_text_1 TEXT,
        facility_text_2 TEXT,
        facility_text_3 TEXT,
        facility_text_4 TEXT,
        facility_text_5 TEXT,
        facility_text_6 TEXT,

        service_subtitle TEXT,
        service_heading TEXT,
        service_description TEXT,
        service_title_1 TEXT,
        service_text_1 TEXT,
        service_title_2 TEXT,
        service_text_2 TEXT,
        service_title_3 TEXT,
        service_text_3 TEXT,
        service_title_4 TEXT,
        service_text_4 TEXT,
        service_title_5 TEXT,
        service_text_5 TEXT,
        service_title_6 TEXT,
        service_text_6 TEXT,

        work_subtitle TEXT,
        work_heading TEXT,
        work_description TEXT,
        work_image_1 INT(11) UNSIGNED DEFAULT '0' NOT NULL,
        work_image_2 INT(11) UNSIGNED DEFAULT '0' NOT NULL,
        work_list_item_1 TEXT,
        work_list_item_2 TEXT,
        work_list_item_3 TEXT,
        work_list_item_4 TEXT,
        work_learn_more_link TEXT,
        work_counter_percentage INT(11) DEFAULT '0' NOT NULL,
        work_counter_percentage_text TEXT,
        work_counter_solutions INT(11) DEFAULT '0' NOT NULL,
        work_counter_solutions_text TEXT,
        work_counter_years INT(11) DEFAULT '0' NOT NULL,
        work_counter_years_text TEXT,
        facility_title_1 TEXT,
        facility_description_1 TEXT,
        facility_title_2 TEXT,
        facility_description_2 TEXT,
        facility_title_3 TEXT,
        facility_description_3 TEXT,
        facility_title_4 TEXT,
        facility_description_4 TEXT,

        video_url TEXT,
        video_image INT(11) UNSIGNED DEFAULT '0' NOT NULL,
        play_button_text VARCHAR(30) DEFAULT 'play' NOT NULL,
        cursor_text VARCHAR(30) DEFAULT 'Play' NOT NULL,

        gallery_images INT(11) UNSIGNED DEFAULT '0' NOT NULL,
        btn_text VARCHAR(50) DEFAULT 'view gallery' NOT NULL,
        btn_link TEXT,

        gallery_with_Button_subtitle TEXT,
        gallery_with_Button_heading TEXT,
        gallery_with_Button_description TEXT,

        section_subtitle TEXT,
        section_title TEXT,
        section_description TEXT,
        testimonial1_text TEXT,
        testimonial1_author TEXT,
        testimonial1_image INT(11) UNSIGNED DEFAULT '0' NOT NULL,
        testimonial1_rating INT(11) DEFAULT '5' NOT NULL,
        testimonial2_text TEXT,
        testimonial2_author TEXT,
        testimonial2_image INT(11) UNSIGNED DEFAULT '0' NOT NULL,
        testimonial2_rating INT(11) DEFAULT '5' NOT NULL,
        testimonial3_text TEXT,
        testimonial3_author TEXT,
        testimonial3_image INT(11) UNSIGNED DEFAULT '0' NOT NULL,
        testimonial3_rating INT(11) DEFAULT '5' NOT NULL,
        testimonial4_text TEXT,
        testimonial4_author TEXT,
        testimonial4_image INT(11) UNSIGNED DEFAULT '0' NOT NULL,
        testimonial4_rating INT(11) DEFAULT '5' NOT NULL,
        testimonial5_text TEXT,
        testimonial5_author TEXT,
        testimonial5_image INT(11) UNSIGNED DEFAULT '0' NOT NULL,
        testimonial5_rating INT(11) DEFAULT '5' NOT NULL,


        faq_title text,
        faq_subtitle text,
        faq_image int(11) unsigned DEFAULT '0' NOT NULL,
        faq_question_1 text,
        faq_answer_1 text,
        faq_question_2 text,
        faq_answer_2 text,
        faq_question_3 text,
        faq_answer_3 text,
        faq_question_4 text,
        faq_answer_4 text,
        faq_question_5 text,
        faq_answer_5 text,
        faq_question_6 text,
        faq_answer_6 text,
        faq_question_7 text,
        faq_answer_7 text,
        faq_question_8 text,
        faq_answer_8 text,
        faq_question_9 text,
        faq_answer_9 text,
        faq_question_10 text,
        faq_answer_10 text,

        tri_link text,
        cetiri_link text,
        pet_link text,
        sest_link text,
        sedam_link text,


        location_image int(11) unsigned DEFAULT '0' NOT NULL,
        email_image int(11) unsigned DEFAULT '0' NOT NULL,
        phone_image int(11) unsigned DEFAULT '0' NOT NULL,

        google_map_url text,
        form_recipient text,
        submit_button_text text,
        name_placeholder text,
        email_placeholder text,
        phone_placeholder text,
        message_placeholder text,




);
