rootPageId: 1
base: /
baseVariants: {}
languages:
  - title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    hreflang: en-US
    direction: ltr
    flag: us
  - title: German
    enabled: true
    languageId: 1
    base: /de/
    locale: de_DE.UTF-8
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ltr
    flag: de
errorHandling: {}
routes: {}
