base: "staklene-pregrade.rs"
errorHandling:
  - errorCode: 404
    errorHandler: Fluid
languages:
  - title: Serbian
    enabled: true
    languageId: 0
    base: /
    locale: sr_RS.UTF-8
    navigationTitle: "Српски / Srpski"
    flag: rs
    hreflang: sr-RS
    websiteTitle: "Staklene pregrade"
    dependencies:
      - typo3/seo-sitemap
    fallbackType: strict
    fallbacks: ""
  - title: English
    enabled: true
    languageId: 1
    base: /en/
    locale: en_US.UTF-8
    navigationTitle: English
    flag: gb
    hreflang: en-US
    websiteTitle: "Glass partitions"
    fallbackType: fallback
    fallbacks: "0"
  - title: German
    enabled: true
    languageId: 2
    base: /de/
    locale: de_DE.UTF-8
    navigationTitle: Deutsch
    flag: de
    hreflang: de-DE
    websiteTitle: "Glasabtrennungen"
    fallbackType: fallback
    fallbacks: "0,1"
  - title: Chinese
    enabled: true
    languageId: 3
    base: /zh/
    locale: zh_CN.UTF-8
    navigationTitle: Chinese
    hreflang: zh-CN
    fallbackType: fallback
    fallbacks: "0,2,1"
    websiteTitle: 铝合金门窗
    flag: cn
rootPageId: 45
websiteTitle: "Staklene pregrade"
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      /: 0
      sitemap.xml: 1533906435
  NewsPlugin:
    type: Extbase
    extension: News
    plugin: Pi1
    routes:
      - routePath: "/vest/{news_title}"
        _controller: "News::detail"
        _arguments:
          news_title: news
    aspects:
      news_title:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_news
        routeFieldName: path_segment
        routeValuePrefix: ""
