base: 'http://pvc-stolarija.local/'
errorHandling:
  -
    errorCode: 404
    errorHandler: Fluid
languages:
  -
    title: Serbian
    enabled: true
    languageId: 0
    base: /
    locale: sr_RS.UTF-8
    navigationTitle: 'Српски / Srpski'
    flag: rs
    hreflang: sr-RS
    websiteTitle: 'Aluminijumska stolarija'
  -
    title: English
    enabled: true
    languageId: 1
    base: /en/
    locale: en_US.UTF-8
    navigationTitle: English
    flag: gb
    hreflang: en-US
    websiteTitle: 'Aluminum Joinery'
    fallbackType: fallback
    fallbacks: '0,2,3'
  -
    title: German
    enabled: true
    languageId: 2
    base: /de/
    locale: de_DE.UTF-8
    navigationTitle: Deutsch
    flag: de
    hreflang: de-DE
    websiteTitle: Aluminium-Fenster
    fallbackType: fallback
    fallbacks: '0,1,3'
  -
    title: Chinese
    enabled: true
    languageId: 3
    base: /zh/
    locale: zh_CN.UTF-8
    navigationTitle: Chinese
    hreflang: zh-CN
    fallbackType: fallback
    fallbacks: '0,2,1'
    websiteTitle: 铝合金门窗
    flag: cn
rootPageId: 1
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      /: 0
      sitemap.xml: 1533906435
websiteTitle: 'Aluminijumska stolarija'
